// <auto-generated />
using Infinite.Core.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InfiniteApi.Migrations
{
    [DbContext(typeof(InfiniteContext))]
    [Migration("20220610220312_Cupom")]
    partial class Cupom
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("InfiniteApi.Entities.CupomEntity", b =>
                {
                    b.Property<int>("CupomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasColumnType("text");

                    b.HasKey("CupomId");

                    b.ToTable("Cupom");
                });
#pragma warning restore 612, 618
        }
    }
}
